spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/final_01
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        show_sql: true
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog.yml
    contexts: dev